# Generated by Django 4.2 on 2023-05-19 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_subscriber', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('econ_indicator_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_1', to='indicators.indicator')),
                ('econ_indicator_10', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_10', to='indicators.indicator')),
                ('econ_indicator_10_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_10_prior', to='indicators.indicator')),
                ('econ_indicator_11', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_11', to='indicators.indicator')),
                ('econ_indicator_11_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_11_prior', to='indicators.indicator')),
                ('econ_indicator_1_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_1_prior', to='indicators.indicator')),
                ('econ_indicator_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_2', to='indicators.indicator')),
                ('econ_indicator_2_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_2_prior', to='indicators.indicator')),
                ('econ_indicator_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_3', to='indicators.indicator')),
                ('econ_indicator_3_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_3_prior', to='indicators.indicator')),
                ('econ_indicator_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_4', to='indicators.indicator')),
                ('econ_indicator_4_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_4_prior', to='indicators.indicator')),
                ('econ_indicator_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_5', to='indicators.indicator')),
                ('econ_indicator_5_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_5_prior', to='indicators.indicator')),
                ('econ_indicator_6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_6', to='indicators.indicator')),
                ('econ_indicator_6_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_6_prior', to='indicators.indicator')),
                ('econ_indicator_7', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_7', to='indicators.indicator')),
                ('econ_indicator_7_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_7_prior', to='indicators.indicator')),
                ('econ_indicator_8', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_8', to='indicators.indicator')),
                ('econ_indicator_8_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_8_prior', to='indicators.indicator')),
                ('econ_indicator_9', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_9', to='indicators.indicator')),
                ('econ_indicator_9_prior', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='econ_indicator_9_prior', to='indicators.indicator')),
                ('report_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subscriber')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
