# Generated by Django 4.2 on 2023-05-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_series_id', models.CharField(unique=True)),
                ('indicator_full_name', models.CharField(unique=True)),
                ('indicator_abbr_name', models.CharField(unique=True)),
                ('indicator_description', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'indicator_references',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicator_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicatorreference')),
            ],
            options={
                'db_table': 'indicators',
            },
        ),
    ]
