# Generated by Django 4.2 on 2023-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicatorreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='indicatorreference',
            name='indicator_description',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorreference',
            name='indicator_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorreference',
            name='indicator_series_id',
            field=models.CharField(unique=True),
        ),
    ]
