# Generated by Django 4.2 on 2023-05-19 21:19

from django.db import migrations

def add_indicator_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IndicatorReference = apps.get_model("indicators", "IndicatorReference")
    for person in Person.objects.all():
        person.name = f"{person.first_name} {person.last_name}"
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_created_at_and_more'),
    ]

    operations = [
    ]
